### PR TITLE
KSP 1.0.x - 64k Kopernicus updates - WIP

### PR DESCRIPTION
**Pull request by Felger**
Made a first pass to the planets based on the new Kopernicus in work on the KSP-RO github ([link](https://github.com/KSP-RO/Kopernicus/tree/revertBranch))
Done:
* Resized planets and orbits to match the old RSS configs.
* Added some some basic configs for other mod compatibility
* Procedural Parts - Allow bigger tanks earlier in the tech tree. You'll need them to get outside the atmosphere.
* RemoteTech - Modified the settings file to increase antenna range. May have left a few other ground stations in the config.  

To Do:
* Update atmospheres.  Kerbin's has been rescaled using the scales calculated in Real Solar System, with the max heights scaled to the 64k atmosphere.  Something similar needs to happen for all other atmospheres, or use the legacy atmosphere scaling and set scale height/max height/etc
* PQS scaling needs to be updated, right now everything's a tad flat.
* Tinker with the KSC Switcher config to get the space center in the right spot.
* Follow the Kopernicus development, wait for a proper release to finalize configs.
* Set up installation via CKAN for ease of use.

### CODE REVIEW

**Comment by Felger** [comment]
Updated Kopernicus to the latest dev version KSC switcher doesn't work, but the built-in space center should work nicely.

**Comment by Felger** [comment]
New update, KSC is properly repositioned, atmospheres are properly scaled (might need to check on appearance from surface, there's a few settings I didn't tweak)

**Comment by Felger** [comment]
Commenting here so I don't forget:
Recommend setting default re-entry heat to 40%.  Calibrated to 3-man capsule mun return trajectory.  Will need tougher heat shield to survive more than that.

**Comment by Paul-kingtiger** [comment]
I wonder if there is a way to set the reentry heating via modmanager?  I'll look into it.

**Comment by Felger** [comment]
To do:
Figure out PQS
Figure out how to adjust the atmosphere glow to get rid of that white bar on Kerbin (check other planets too)

**Comment by Felger** [comment]
https://github.com/BryceSchroeder/Kopernicus/releases

Kopernicus 0.0.7 has released, guess it's time to get around to releasing this.

**Comment by Felger** [comment]
Got stuff pretty much ready to go, added the CKAN files so the release can be handled nicely.

Everything should be working and ready to go for release!

**Comment by Paul-kingtiger** [comment]
Awesome. I'm away from my computer all day at a birthday, but I'll test everything tomorrow. If you want to release now I can add you to the mod on Kerbal stuff. Tried Felger but its not coming up, do you have an account?

Sent from my Windows Phone
________________________________

**Comment by Felger** [comment]
I have an account, Felger, but I don't have any mods published by my name (Everything else I've worked on, just published on Github).  Just checked on there, guess it was private.

https://kerbalstuff.com/profile/Felger

**Comment by Paul-kingtiger** [comment]
I've added to to the mod, so you're all set

Sent from my Windows Phone
________________________________

**Comment by Felger** [comment]
As much as I'd like to get the official release out soon, let's get it properly / independently tested.  I also removed ModuleManager and Kopernicus from the bundle, that way we don't have to update our release every time either of those updates.

I'll also get the CKAN files added to the repository so that'll be ready to go when we release as well.

**Pull request merged**
