### PR TITLE
Heating Tweak

### PR DESCRIPTION
**Pull request by seanyoung247**

### CODE REVIEW

**Comment by Felger** [comment]
This looks good to me, merging

**Comment by Tellion** [comment]
Something will have to be done about spaceplanes though

**Comment by Felger** [comment]
Well, it's better than nothing for the moment.

**Comment by Tellion** [comment]
Yeah, sure is.

**Comment by seanyoung247** [comment]
I had a brief look at spaceplanes, though initially only really was looking
to balance something for pods. TBH I've been having trouble getting
spaceplanes back in stock recently 0.o. For a straight heating tweak the
options would be to up the heat resistance and/or conduction of spaceplane
parts, or dial down the heating more I would think.

**Pull request merged**
